package com.mockengine.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.Map;
import java.util.regex.Pattern;

@RestController
public class DynamicMockController {

    private JsonNode openApiSpec;

    // This runs automatically when the server starts
    @PostConstruct
    public void init() {
        try {
            ObjectMapper mapper = new ObjectMapper();
            // Look for the JSON file generated by our Python script in the root directory
            File file = new File("../openapi-mock.json");
            if (file.exists()) {
                openApiSpec = mapper.readTree(file);
                System.out.println("✅ Successfully loaded openapi-mock.json");
            } else {
                System.out.println("⚠️ Warning: openapi-mock.json not found!");
            }
        } catch (IOException e) {
            System.err.println("Error parsing JSON: " + e.getMessage());
        }
    }

    // Intercept EVERY incoming HTTP request (e.g., GET /api/users/123)
    @RequestMapping(value = "/**", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<JsonNode> handleRequest(HttpServletRequest request) {
        if (openApiSpec == null || !openApiSpec.has("paths")) {
            return ResponseEntity.notFound().build();
        }

        String requestUri = request.getRequestURI();

        // Add a friendly welcome message for the root URL
        if (requestUri.equals("/")) {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode welcomeNode = mapper.createObjectNode()
                .put("message", "Welcome to the Intelligent API Mocking Engine!")
                .put("status", "Server is running successfully")
                .put("hint", "Try accessing your mocked endpoint like /api/users/123");
            return ResponseEntity.ok(welcomeNode);
        }

        String requestMethod = request.getMethod().toLowerCase();
        JsonNode paths = openApiSpec.get("paths");

        // Iterate through our OpenAPI contract to find a matching route
        Iterator<Map.Entry<String, JsonNode>> fields = paths.fields();
        while (fields.hasNext()) {
            Map.Entry<String, JsonNode> entry = fields.next();
            String pathStr = entry.getKey();
            
            // Magic Trick: Convert OpenAPI path parameters like {id} into a Regex pattern
            // So "/api/users/{id}" matches "/api/users/99" or "/api/users/abc"
            String regexPath = pathStr.replaceAll("\\{[^/]+\\}", "[^/]+");
            
            if (Pattern.matches(regexPath, requestUri)) {
                JsonNode methodNode = entry.getValue().get(requestMethod);
                
                if (methodNode != null) {
                    // Extract the mocked example response generated by the LLM
                    JsonNode responses = methodNode.get("responses");
                    if (responses != null && responses.has("200")) {
                        JsonNode content = responses.get("200").get("content");
                        if (content != null && content.has("application/json")) {
                            JsonNode example = content.get("application/json").get("example");
                            if (example != null) {
                                return ResponseEntity.ok(example);
                            }
                        }
                    }
                    // Fallback if the AI structured the JSON slightly differently
                    return ResponseEntity.ok(methodNode);
                }
            }
        }
        
        // If the URL doesn't match anything in our JSON, return a 404 Not Found
        return ResponseEntity.notFound().build();
    }
}